name: "Teams Notifications"
description: "Send notification from github workflow to teams channel"
author: "Vinayak Jadhav"

inputs:
  gh-token:
    description: "Github Token or Pat Token"
    required: true
  notification-summary:
    description: "notification summary:"
    required: true
  msTeams-webhook-uri:
    description: "msTeams webhook uri"
    required: true
  notification-colour:
    description: "notification colour"
    type: choice
    required: true
    options:
    - good
    - attention
    - accent
  notification-type:
    description: "Github Token or Pat Token"
    required: true
    type: choice
    options:
    - deployment
    - infomation

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "white"