name: Build

on: 
  workflow_dispatch:
  push:


jobs:
  Build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./
      with:
        gh-token: ${{ github.token }}
        notification-summary: "Deployment test"
        msTeams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
        notification-colour: 'good'